# Generated by Django 4.2.2 on 2023-07-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='catogery',
        ),
    ]
