# Generated by Django 4.2.2 on 2023-07-24 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variant_discount_price'),
        ('banners', '0004_remove_banner_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
    ]
