# Generated by Django 4.2.2 on 2023-07-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_wallet_wallet_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
