# Generated by Django 4.2.2 on 2023-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
