# Generated by Django 4.2.2 on 2023-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0002_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('CANCELLED', 'cancelled'), ('DELIVERED', 'Delivered'), ('ORDERED', 'Ordered'), ('RETURNED', 'Returned'), ('SHIPPED', 'Shipped'), ('PROCESSING', 'processing')], default='ordered', max_length=20),
        ),
    ]
