# Generated by Django 4.2.2 on 2023-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0004_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('ORDERED', 'Ordered'), ('RETURNED', 'Returned'), ('SHIPPED', 'Shipped'), ('PROCESSING', 'Processing')], default='ordered', max_length=20, null=True),
        ),
    ]
