# Generated by Django 4.2.2 on 2023-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('ORDERED', 'Ordered'), ('RETURNED', 'Returned'), ('SHIPPED', 'Shipped'), ('PROCESSING', 'Processing'), ('RETURN', 'return')], default='ordered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('RAZORPAY', 'RazorPay'), ('WALLET', 'Wallet')], max_length=20),
        ),
    ]
