# Generated by Django 4.2.2 on 2023-07-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
